package com.f0rgiv.lethani;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.web.servlet.MockMvc;

import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import static org.hamcrest.Matchers.*;

@SpringBootTest
@AutoConfigureMockMvc
class DemoApplicationTests {

	@Autowired
	MockMvc mockMvc;

	@Test
	void contextLoads() {
	}

	@Test
	void testHomePage() throws Exception {
		mockMvc.perform(get("/"))
				.andDo(print())
				.andExpect(content().string(containsString("<div class=\"home-container\">")))
				.andExpect(content().string(containsString("<div class=\"welcome-div\">")))
				.andExpect(content().string(containsString("<!--Dragon https://codepen.io/JD_Rocks/pen/eidHp -->")))
				.andExpect(content().string(containsString("<div>")))
				.andExpect(content().string(containsString("<div class='dragon'>")))
				.andExpect(content().string(containsString("<div class='graphic'>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<h1 class=\"h1-home\">Welcome to Lethani!</h1>")))
				.andExpect(content().string(containsString("<img class=\"img-castle-town\" src=\"/assets/castle-town.jpeg\" alt=\"Castle Town\">")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<p>################################################</p>")))
				.andExpect(content().string(containsString("<p>########....####.....Log in below!.....####....########</p>")))
				.andExpect(content().string(containsString("<p>########...#####...Play the game!...#####...########</p>")))
				.andExpect(content().string(containsString("<p>###....Don't have an account yet, sign up today!....###</p>")))
				.andExpect(content().string(containsString("<p>###########...................................###########</p>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<!--Fire Animation from https://codepen.io/yamanda/pen/RpNMaY-->")))
				.andExpect(content().string(containsString("<div class=\"fire-animation\">")))
				.andExpect(content().string(containsString("<div class=\"fire\">")))
				.andExpect(content().string(containsString(" <div class=\"fire-left\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"particle-fire\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"fire-main\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"particle-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"fire-right\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"particle-fire\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"fire-bottom\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"fire-animation\">")))
				.andExpect(content().string(containsString("<div class=\"fire-two\">")))
				.andExpect(content().string(containsString(" <div class=\"fire-left\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"particle-fire\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"fire-main\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"particle-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"fire-right\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"particle-fire\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"fire-bottom\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<h2>Log In</h2>")))
				.andExpect(content().string(containsString("<div class=\"col-10 mx-auto col-lg-5\">")))
				.andExpect(content().string(containsString("<form class=\"p-5 border rounded-3 bg-light\" action=\"/login\" method=\"post\">")))
				.andExpect(content().string(containsString("<div class=\"form-floating mb-3\">")))
				.andExpect(content().string(containsString("<input class=\"form-control\" id=\"input-username\" type=\"text\" name=\"username\" required>")))
				.andExpect(content().string(containsString("<label class=\"floatingInput\" for=\"input-username\">username</label>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"form-floating mb-3\">")))
				.andExpect(content().string(containsString("<input class=\"form-control\" id=\"input-password\" type=\"password\" name=\"password\" required>")))
				.andExpect(content().string(containsString("<label class=\"floatingInput\" for=\"input-password\">password</label>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<input class=\"w-100 btn btn-lg btn-primary\" type=\"submit\" value=\"Log In\">")))
				.andExpect(content().string(containsString("<div>Don't have an account yet? <a class=\"col-lg-3\" href=\"/signup\">Sign Up</a></div>")))
				.andExpect(content().string(containsString("</form>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(status().isOk());
	}

	@Test
	void testLoginPage() throws Exception {
		mockMvc.perform(get("/login"))
				.andDo(print())
				.andExpect(content().string(containsString("<!--Fire Animation from https://codepen.io/yamanda/pen/RpNMaY-->")))
				.andExpect(content().string(containsString("<div class=\"fire-animation\">")))
				.andExpect(content().string(containsString("<div class=\"fire\">")))
				.andExpect(content().string(containsString(" <div class=\"fire-left\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"particle-fire\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"fire-main\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"particle-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"fire-right\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"particle-fire\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"fire-bottom\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"fire-animation\">")))
				.andExpect(content().string(containsString("<div class=\"fire-two\">")))
				.andExpect(content().string(containsString(" <div class=\"fire-left\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"particle-fire\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"fire-main\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"particle-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"fire-right\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"particle-fire\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"fire-bottom\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<h2>Log In</h2>")))
				.andExpect(content().string(containsString("<div class=\"col-10 mx-auto col-lg-5\">")))
				.andExpect(content().string(containsString("<form class=\"p-5 border rounded-3 bg-light\" action=\"/login\" method=\"post\">")))
				.andExpect(content().string(containsString("<div class=\"form-floating mb-3\">")))
				.andExpect(content().string(containsString("<input class=\"form-control\" id=\"input-username\" type=\"text\" name=\"username\" required>")))
				.andExpect(content().string(containsString("<label class=\"floatingInput\" for=\"input-username\">username</label>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"form-floating mb-3\">")))
				.andExpect(content().string(containsString("<input class=\"form-control\" id=\"input-password\" type=\"password\" name=\"password\" required>")))
				.andExpect(content().string(containsString("<label class=\"floatingInput\" for=\"input-password\">password</label>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<input class=\"w-100 btn btn-lg btn-primary\" type=\"submit\" value=\"Log In\">")))
				.andExpect(content().string(containsString("<div>Don't have an account yet? <a class=\"col-lg-3\" href=\"/signup\">Sign Up</a></div>")))
				.andExpect(content().string(containsString("</form>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(status().isOk());
	}

	@Test
	void testSignUpPage() throws Exception {
		mockMvc.perform(get("/signup"))
				.andDo(print())
				.andExpect(content().string(containsString("<!--Fire Animation from https://codepen.io/yamanda/pen/RpNMaY-->")))
				.andExpect(content().string(containsString("<div class=\"fire-animation\">")))
				.andExpect(content().string(containsString("<div class=\"fire\">")))
				.andExpect(content().string(containsString(" <div class=\"fire-left\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"particle-fire\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"fire-main\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"particle-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"fire-right\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"particle-fire\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"fire-bottom\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"fire-animation\">")))
				.andExpect(content().string(containsString("<div class=\"fire-two\">")))
				.andExpect(content().string(containsString(" <div class=\"fire-left\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"particle-fire\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"fire-main\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"particle-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"fire-right\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("<div class=\"particle-fire\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"fire-bottom\">")))
				.andExpect(content().string(containsString("<div class=\"main-fire\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<h1 class=\"h3 mb-3 fw-normal\">Sign Up</h1>")))
				.andExpect(content().string(containsString("<div class=\"col-10 mx-auto col-lg-5\">")))
				.andExpect(content().string(containsString("<form class=\"p-5 border rounded-3 bg-light\" action=\"/signup\" method=\"post\">")))
				.andExpect(content().string(containsString("<div class=\"form-floating mb-3\">")))
				.andExpect(content().string(containsString("<input class=\"form-control\" id=\"input-username\" type=\"text\" name=\"username\" required>")))
				.andExpect(content().string(containsString("<label class=\"floatingInput\" for=\"input-username\">username</label>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"form-floating mb-3\">")))
				.andExpect(content().string(containsString("<input class=\"form-control\" id=\"input-password\" type=\"password\" name=\"password\" required>")))
				.andExpect(content().string(containsString("<label class=\"floatingInput\" for=\"input-password\">password</label>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<input class=\"w-100 btn btn-lg btn-secondary\" type=\"submit\" value=\"Sign Up\">")))
				.andExpect(content().string(containsString("<div>Already have an account? <a href=\"/login\">Log In</a></div>")))
				.andExpect(content().string(containsString("</form>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div th:if=\"${errorMessage}\" class=\"alert\">")))
				.andExpect(content().string(containsString("<th:block th:text=\"${errorMessage}\"></th:block>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(status().isOk());
	}

	@Test
	void testPlayPage() throws Exception {
		mockMvc.perform(get("/play"))
				.andDo(print())
				.andExpect(content().string(containsString("<div class=\"bodyDiv\">")))
				.andExpect(content().string(containsString("<header th:replace=\"fragments/header :: header\"></header>")))
				.andExpect(content().string(containsString("<main id=\"main\">")))
				.andExpect(content().string(containsString("<div id=\"place\">")))
				.andExpect(content().string(containsString("<div class=\"gameDiv\"></div>")))
				.andExpect(content().string(containsString("<div class=\"deathDiv\">")))
				.andExpect(content().string(containsString("<h1 id=\"deathNote\">You have Died</h1>")))
				.andExpect(content().string(containsString("<button id=\"deathButton\">Respawn!</button>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div id=\"gameBoardContainer\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"messStats\">")))
				.andExpect(content().string(containsString("<div class=\"stats\">")))
				.andExpect(content().string(containsString("<div class=\"hpDiv\">")))
				.andExpect(content().string(containsString("<h3>HP:    </h3>")))
				.andExpect(content().string(containsString("<div id=\"hpBar\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"xpDiv\">")))
				.andExpect(content().string(containsString("<h3 id=\"xpScore\" th:text=\"'XP: ' + ${userPrincipal.character.xp}\"></h3>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"hpDiv\">")))
				.andExpect(content().string(containsString("<h3>Mob HP:    </h3>")))
				.andExpect(content().string(containsString("<div id=\"mobHpBar\"></div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div class=\"messageDiv\">")))
				.andExpect(content().string(containsString("<div id=\"messageTable\"></div>")))
				.andExpect(content().string(containsString("<div class=\"messageInput\">")))
				.andExpect(content().string(containsString("<form class=\"messageFormField\" name=\"messageForm\">")))
				.andExpect(content().string(containsString("<input type=\"text\" id=\"messageField\" placeholder=\"Send a message!\">")))
				.andExpect(content().string(containsString("<input id=\"messageSubmit\" type=\"submit\">")))
				.andExpect(content().string(containsString("</form>")))
				.andExpect(content().string(containsString("<ul class=\"play-ul\">")))
				.andExpect(content().string(containsString("<li class=\"play-li\"><bold>How to play:</bold></li>")))
				.andExpect(content().string(containsString("<li>To go up - hit the w key</li>")))
				.andExpect(content().string(containsString("<li>To go down - hit the s key</li>")))
				.andExpect(content().string(containsString("<li>To go right - hit the d key</li>")))
				.andExpect(content().string(containsString("<li>To go left - hit the a key</li>")))
				.andExpect(content().string(containsString("<li>To use a potion - hit the q key</li>")))
				.andExpect(content().string(containsString("<li>To attack the mobs/other players - run into them</li>")))
				.andExpect(content().string(containsString("<li>@ - your character</li>")))
				.andExpect(content().string(containsString("<li>0 - other players</li>")))
				.andExpect(content().string(containsString("<li>& -  mobs</li>")))
				.andExpect(content().string(containsString("<li>&& - mob boss</li>")))
				.andExpect(content().string(containsString("<li>##### - walls</li>")))
				.andExpect(content().string(containsString("<li>.... - area you can move around in</li>")))
				.andExpect(content().string(containsString("<li>% - plants</li>")))
				.andExpect(content().string(containsString("<li>$$ - store counter</li>")))
				.andExpect(content().string(containsString("<li>P - potions</li>")))
				.andExpect(content().string(containsString("<li>XX - entrance/exit to different zones</li>")))
				.andExpect(content().string(containsString("</ul>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(status().isOk());
	}

	@Test
	void testLeaderBoardPage() throws Exception {
		mockMvc.perform(get("/leaderboard"))
				.andDo(print())
				.andExpect(content().string(containsString("<div id=\"leader-page-container\">")))
				.andExpect(content().string(containsString("<div id=\"leader-content-wrapper\">")))
				.andExpect(content().string(containsString("<div id=\"leaderboard-title\">")))
				.andExpect(content().string(containsString("<h1>Leader Board</h1>")))
				.andExpect(content().string(containsString("<p class=\"p-leader\">See who has the highest score!</p>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<img class=\"leader-img\" src=\"/assets/haunted-woods.jpeg\" alt=\"Woods\">")))
				.andExpect(content().string(containsString("<div class=\"users-leaders\">")))
				.andExpect(content().string(containsString("<div class=\"user-class-score\" th:each=\"highScore : ${highScores}\">")))
				.andExpect(content().string(containsString("<div>")))
				.andExpect(content().string(containsString("<img id=\"profile-img-two\" alt=\"profile picture\" loading=\"lazy\"")))
				.andExpect(content().string(containsString("th:src=\"${@appUserService.getProfilePicturePath(highScore.userPrincipal)}\">")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div>")))
				.andExpect(content().string(containsString("<img id=\"class-img-two\" th:src=\"'/assets/' + ${highScore.characterClass} + '.png'\">")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("<div>")))
				.andExpect(content().string(containsString("<ul class=\"leader-ul\">")))
				.andExpect(content().string(containsString("<li th:text=\"${highScore.name}\">Username </li>")))
				.andExpect(content().string(containsString("<li th:text=\"${highScore.characterClass}\">Class</li>")))
				.andExpect(content().string(containsString("<li th:text=\"${highScore.highScore}\">XP</li>")))
				.andExpect(content().string(containsString("</ul>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(content().string(containsString("</div>")))
				.andExpect(status().isOk());
	}

	//TODO: Add more tests for other pages.

	@Test
	void testProfilePage() throws Exception {
		mockMvc.perform(get("/profile"))
				.andDo(print())
				.andExpect(status().isOk());
	}

	@Test
	void testAboutUsPage() throws Exception {
		mockMvc.perform(get("/about"))
				.andDo(print())
				.andExpect(status().isOk());
	}


}
